package com.example.appmusic.common

object PrefsKey {
    const val KEY_TUTORIAL_DONE = "KEY_TUTORIAL_DONE"
    const val KEY_SHARE_ANALYTICS = "KEY_SHARE_ANALYTICS"
    const val KEY_IS_FIRST_INSTALL = "KEY_IS_FIRST_INSTALL"
    const val KEY_SETTING_START_DAY_OF_WEEK = "KEY_SETTING_START_DAY_OF_WEEK"
    const val KEY_SETTING_NUMBER_DISPLAY_LINE = "KEY_SETTING_NUMBER_DISPLAY_LINE"
    const val KEY_GET_JAPAN_HOLIDAY_JSON_DATE = "KEY_GET_JAPAN_HOLIDAY_JSON_DATE"
    const val KEY_THEME_COLOR_INDEX = "KEY_THEME_COLOR_INDEX"
    const val KEY_VALUE_REMINDER_HOUR = "KEY_VALUE_REMINDER_HOUR"
    const val KEY_VALUE_REMINDER_MINUTES = "KEY_VALUE_REMINDER_MINUTES"
    const val KEY_VALUE_SETTING_REMINDERS = "KEY_VALUE_SETTING_REMINDERS"
    const val KEY_SETTING_PASS_CODE = "KEY_SETTING_PASS_CODE"
    const val KEY_TEXT_SETTING = "KEY_TEXT_SETTING"
    const val KEY_LANGUAGE_SETTING = "KEY_LANGUAGE_SETTING"
    const val KEY_INSTALL_APP_TIME_TS = "KEY_INSTALL_APP_TIME_TS"
    const val KEY_REMOVED_ADS_STATE = "KEY_REMOVED_ADS_STATE"
    const val KEY_OPEN_APP_COUNT = "KEY_OPEN_APP_COUNT"
    const val KEY_IS_RESET_COUNTING_TO_SHOW_REVIEW = "KEY_IS_RESET_COUNTING_TO_SHOW_REVIEW"
    const val KEY_IS_GOTO_ANDROID_REVIEW_DIALOG = "KEY_IS_GOTO_ANDROID_REVIEW_DIALOG"
    const val KEY_END_TIME_CREATE_DIARY = "KEY_END_TIME_CREATE_DIARY"
    const val KEY_PRICE_ADS = "KEY_PRICE_ADS"

}
